create table if not exists public.threats (
    "threatId" text primary key,
    title text,
    description text,
    "eventTime" timestamptz,
    location jsonb,
    category text,
    severity text,
    status text,
    "impactedSectors" jsonb default '[]'::jsonb,
    indicators jsonb default '[]'::jsonb,
    sources jsonb default '[]'::jsonb,
    confidence integer,
    "secondaryTags" jsonb default '[]'::jsonb,
    "relatedThreats" jsonb default '[]'::jsonb,
    "createdAt" timestamptz default now(),
    "updatedAt" timestamptz default now()
);

create table if not exists public.rss_feeds (
    id bigint generated by default as identity primary key,
    url text unique not null,
    name text,
    enabled boolean default true,
    "createdAt" timestamptz default now(),
    "updatedAt" timestamptz default now()
);

create index if not exists threats_category_idx on public.threats (category);
create index if not exists threats_severity_idx on public.threats (severity);
create index if not exists threats_event_time_idx on public.threats ("eventTime" desc);
create index if not exists threats_status_idx on public.threats (status);